### ISSUE TITLE
thonkutil 2.11.0+1.18 crash

### ISSUE THREAD

**Issue by Eldoradoge** [LimeAppleBoat/ThonkUtil#12]
[latest.log](https://github.com/LimeAppleBoat/ThonkUtil/files/8336876/latest.log)

**Comment by Eldoradoge** [comment]
my curseforge account is raynesp1der this is the crash i had been getting.

**Comment by Jab125** [comment]
Does it still crash with ThonkUtil 2.12.0?

**Comment by Jab125** [comment]
> 2.12.0
