### ISSUE TITLE
WavyCapes incompatibility

### ISSUE THREAD

**Issue by Niketats** [LimeAppleBoat/ThonkUtil#13]
capes are invisible if WavyCapes installed

**Comment by Jab125** [comment]
Is currently being worked on.

**Comment by Jab125** [comment]
fixed in d1fb9bd95e66164dac9565e148b06adbac479bf9

**Comment by Jab125** [comment]
Needs to be re-fixed in 1.19

**Comment by Jab125** [comment]
fixed in f1e2020e578cc679adb40e35ce2bcaeed768d573
