### ISSUE TITLE
Console spaming with saving player data

### ISSUE THREAD

**Issue by Polarite** [LimeAppleBoat/ThonkUtil#14]
1.18.2 fabric console gets spammed by thonkutil save player data:false texts, I suppose this is a bug(?)

**Comment by Polarite** [comment]
![image](https://user-images.githubusercontent.com/34978332/160440574-14403f17-9f4c-424b-90dd-4ff4c90a708f.png)
screenshot for explanation

**Comment by dandin87** [comment]
This issue should not have been closed. The updated versions is unusable....
