### ISSUE TITLE
New update makes server fail to start

### ISSUE THREAD

**Issue by uhhams** [LimeAppleBoat/ThonkUtil#18]
my server says the mod is the reason its failing to start and its also putting files in places they shouldnt be. 

https://paste.shockbyte.com/aduwazojaveqawopadif.  <--- start log
<img width="953" alt="Screen Shot 2022-05-04 at 6 53 50 PM" src="https://user-images.githubusercontent.com/96365922/166853561-d826f1de-bc1e-49f8-a44a-d5e06223c129.png">

**Comment by Jab125** [comment]
Use 2.12.x
2.13.x is unstable

**Comment by ThinkWithPbody** [comment]
I appreciate your work putting updates out but as of 2.14.1 the server still can't start. Is 2.12.0 still the stable version for servers?
