### ISSUE TITLE
1.19 Crash With Better Animals Plus

### ISSUE THREAD

**Issue by 123FLO321** [LimeAppleBoat/ThonkUtil#19]
When ThonkUtils and BetterAnimalsPlus are installed the game crashes.
Either on it's own is fine.
Unsure what side the problem is on, since the crash report ist not helpfull.

See crash report here: https://github.com/itsmeow/betteranimalsplus/issues/346

**Comment by itsmeow** [comment]
It's almost definitely on this side, since I do nothing special with tags.

**Comment by aAndrew3030** [comment]
Log with Better Animals, Architectury, and Thonk
[latest.log](https://github.com/LimeAppleBoat/ThonkUtil/files/8884781/latest.log)

**Comment by Jab125** [comment]
Closed in favor of #21
