### ISSUE TITLE
[Issue] Breaks owo-lib's tag injector due to setting a return value in TagGroupLoaderMixin

### ISSUE THREAD

**Issue by Dragon-Seeker** [LimeAppleBoat/ThonkUtil#29]
The mixin dose not need to [return](https://github.com/LimeAppleBoat/ThonkUtil/blob/43b0c822e643361fb63668506ad72bf8cd24a37c/thonkutil-capes-v1/src/main/java/com/jab125/thonkutil/mixin/TagGroupLoaderMixin.java#L68) anything as it is a map meaning you can just get the map and add or modifies the given entries. Returning will cancel the method early causing anyone else injects not to work.

**Comment by Jab125** [comment]
Feel free to make a pull request
