### ISSUE TITLE
Thonkutil breaks all models without a slash in their path

### ISSUE THREAD

**Issue by MattiDragon** [LimeAppleBoat/ThonkUtil#32]
[com.jab125.thonkutil.mixin.ModelLoaderMixin](https://github.com/LimeAppleBoat/ThonkUtil/blob/1.19/thonkutil-capes-v1/src/main/java/com/jab125/thonkutil/mixin/ModelLoaderMixin.java) assumes that all models have a slash in their path and blindly grabs the second part after splitting on it, even if there is no second part. This throws an `ArrayIndexOutOfBoundsException` which prevents the model from loading. You also don't seem to properly support models with more than one slash, but that's rare and just causes the cape to not get a model. 

This breaks the latest version of extended drawers as it includes a template model in it's root model directory.

**Comment by MattiDragon** [comment]
Originally reported here: mattidragon/extendeddrawers#30

**Comment by Jab125** [comment]
you are free to make a pull request for this as i am busy working on other projects right now

**Comment by MattiDragon** [comment]
opened pr #33

**Comment by MattiDragon** [comment]
The PR is merged and I assume released. Should this be closed
