### ISSUE TITLE
Conflict with Trinkets mod | Fabric 1.18.1

### ISSUE THREAD

**Issue by ghost** [LimeAppleBoat/ThonkUtil#4]
**MC Version:** 1.18.1
**Modloader:** Fabric 0.12.12

**Mods used:**
- Fabric API v0.45.0
- Cloth Config API (Fabric) v6.1.48
- **ThonkUtil v2.5.0, v2.4.2, and v 2.2.1**
- Trinkets (Fabric) v3.1.0
- Elytra Trinket (Fabric) v3.0.0
- Icarus (Fabric) v1.9

**Issue:** ThonkUtils v2.5.0 and v2.4.2 is conflicting with other mods over the Trinket's 'cape' slot which prevents the use of the Elytra Trinket mod (allows the elytra to be equipped in the cape slot) and the use of the wings from the Icarus mod (also used in the cape slot). It's possible this happens with others but I have only tested the two mods mentioned above. Not sure where it originates but since ThonkUtil was breaking it first and not the other mods, I wanted to post it here to start with.

**Note:** This isn't an issue when using the 2.2.1 version of the mod in which all the mods work perfectly. This was originally reported to me over the Medieval MC 1.18.1 Fabric modpack, but I tested the set of mods mentioned in a separate profile to confirm the conflict.

**Logs:** This may help show what's happening but it only shows on v2.4.2:
Couldn't load tag trinkets:chest/cape as it is missing following references: thonkutil:minecon_2011_cape (from thonkutil:migration_cape),thonkutil:minecon_2013_cape (from thonkutil:migration_cape),thonkutil:minecon_2015_cape (from thonkutil:migration_cape),thonkutil:minecon_2016_cape (from thonkutil:migration_cape),thonkutil:bacon_cape (from thonkutil:migration_cape),thonkutil:one_millionth_cape (from thonkutil:migration_cape)... (just more cape mentions from ThonkUtil mod)

https://pastebin.com/gJF10gzE

**Comment by Jab125** [comment]
lemme check dat

**Comment by Jab125** [comment]
> Logs: This may help show what's happening but it only shows on v2.4.2:
Couldn't load tag trinkets:chest/cape as it is missing following references: thonkutil:minecon_2011_cape (from thonkutil:migration_cape),thonkutil:minecon_2013_cape (from thonkutil:migration_cape),thonkutil:minecon_2015_cape (from thonkutil:migration_cape),thonkutil:minecon_2016_cape (from thonkutil:migration_cape),thonkutil:bacon_cape (from thonkutil:migration_cape),thonkutil:one_millionth_cape (from thonkutil:migration_cape)... (just more cape mentions from ThonkUtil mod)

This is because thonkutil tried adding the tag in everything, not just tags/items, so irrelevant

**Comment by Jab125** [comment]
i'm gonna test it with the latest build

**Comment by Jab125** [comment]
`{"replace":false,"values":["minecraft:elytra","icarus:white_feathered_wings","icarus:orange_feathered_wings","icarus:magenta_feathered_wings","icarus:light_blue_feathered_wings","icarus:yellow_feathered_wings","icarus:lime_feathered_wings","icarus:pink_feathered_wings","icarus:grey_feathered_wings","icarus:light_grey_feathered_wings","icarus:cyan_feathered_wings","icarus:purple_feathered_wings","icarus:blue_feathered_wings","icarus:brown_feathered_wings","icarus:green_feathered_wings","icarus:red_feathered_wings","icarus:black_feathered_wings","icarus:white_dragon_wings","icarus:orange_dragon_wings","icarus:magenta_dragon_wings","icarus:light_blue_dragon_wings","icarus:yellow_dragon_wings","icarus:lime_dragon_wings","icarus:pink_dragon_wings","icarus:grey_dragon_wings","icarus:light_grey_dragon_wings","icarus:cyan_dragon_wings","icarus:purple_dragon_wings","icarus:blue_dragon_wings","icarus:brown_dragon_wings","icarus:green_dragon_wings","icarus:red_dragon_wings","icarus:black_dragon_wings","icarus:white_mechanical_feathered_wings","icarus:orange_mechanical_feathered_wings","icarus:magenta_mechanical_feathered_wings","icarus:light_blue_mechanical_feathered_wings","icarus:yellow_mechanical_feathered_wings","icarus:lime_mechanical_feathered_wings","icarus:pink_mechanical_feathered_wings","icarus:grey_mechanical_feathered_wings","icarus:light_grey_mechanical_feathered_wings","icarus:cyan_mechanical_feathered_wings","icarus:purple_mechanical_feathered_wings","icarus:blue_mechanical_feathered_wings","icarus:brown_mechanical_feathered_wings","icarus:green_mechanical_feathered_wings","icarus:red_mechanical_feathered_wings","icarus:black_mechanical_feathered_wings","icarus:white_mechanical_leather_wings","icarus:orange_mechanical_leather_wings","icarus:magenta_mechanical_leather_wings","icarus:light_blue_mechanical_leather_wings","icarus:yellow_mechanical_leather_wings","icarus:lime_mechanical_leather_wings","icarus:pink_mechanical_leather_wings","icarus:grey_mechanical_leather_wings","icarus:light_grey_mechanical_leather_wings","icarus:cyan_mechanical_leather_wings","icarus:purple_mechanical_leather_wings","icarus:blue_mechanical_leather_wings","icarus:brown_mechanical_leather_wings","icarus:green_mechanical_leather_wings","icarus:red_mechanical_leather_wings","icarus:black_mechanical_leather_wings","icarus:white_light_wings","icarus:orange_light_wings","icarus:magenta_light_wings","icarus:light_blue_light_wings","icarus:yellow_light_wings","icarus:lime_light_wings","icarus:pink_light_wings","icarus:grey_light_wings","icarus:light_grey_light_wings","icarus:cyan_light_wings","icarus:purple_light_wings","icarus:blue_light_wings","icarus:brown_light_wings","icarus:green_light_wings","icarus:red_light_wings","icarus:black_light_wings","icarus:flandres_wings","icarus:discords_wings","icarus:zanzas_wings","thonkutil:mojang_classic_cape","thonkutil:mojang_cape","thonkutil:mojang_studios_cape","thonkutil:minecon_2011_cape","thonkutil:minecon_2013_cape","thonkutil:minecon_2015_cape","thonkutil:minecon_2016_cape","thonkutil:bacon_cape","thonkutil:one_millionth_cape","thonkutil:dannybstyle_cape","thonkutil:julian_clark_cape","thonkutil:mrmessiah_cape","thonkutil:prismarine_cape","thonkutil:birthday_cape","thonkutil:translator_cape","thonkutil:chinese_translator_cape","thonkutil:japanese_translator_cape","thonkutil:scrolls_champion_cape","thonkutil:cobalt_cape","thonkutil:mojira_moderator_cape","thonkutil:mapmaker_cape","thonkutil:turtle_cape","thonkutil:migration_cape","thonkutil:founders_cape","thonkutil:pan_cape","thonkutil:hero_cape","thonkutil:christmas_2010_cape","thonkutil:new_year_2011_cape","thonkutil:first_birthday_cape","thonkutil:optifine_cape","thonkutil:better_optifine_cape","thonkutil:animated_christmas_2010_cape"]}`

Bug fixed, I'll push out 2.6.0 today
