### ISSUE TITLE
New Tooltip at menu?

### ISSUE THREAD

**Issue by TheButterbrotMan** [LimeAppleBoat/ThonkUtil#8]
https://bytebin.lucko.me/dEFgK3b3Jl

**Comment by TheButterbrotMan** [comment]
Got it working.

**Comment by TheButterbrotMan** [comment]
It seems like the new version adds a tooltip at the menu, that is not disableable.

**Comment by Jab125** [comment]
Will be fixed when I'm out of school

**Comment by TheButterbrotMan** [comment]
Youre really long in school. lol.

**Comment by Jab125** [comment]
@TheButterbrotMan fixed in thonkutil 2.8.0
